# name:      pendule_designer
# author:    Lundrih (https://github.com/EyumLundrih)


# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pendule_designer.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1359, 697)
        self.openGLWidget = QtWidgets.QOpenGLWidget(Dialog)
        self.openGLWidget.setGeometry(QtCore.QRect(10, 20, 781, 661))
        self.openGLWidget.setObjectName("openGLWidget")
        self.graphicsView = PlotWidget(Dialog)
        self.graphicsView.setGeometry(QtCore.QRect(810, 50, 256, 192))
        self.graphicsView.setObjectName("graphicsView")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(860, 30, 191, 20))
        self.label.setObjectName("label")
        self.graphicsView_2 = PlotWidget(Dialog)
        self.graphicsView_2.setGeometry(QtCore.QRect(810, 270, 536, 192))
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.graphicsView_3 = PlotWidget(Dialog)
        self.graphicsView_3.setGeometry(QtCore.QRect(810, 490, 536, 192))
        self.graphicsView_3.setObjectName("graphicsView_3")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(870, 250, 131, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(1180, 30, 91, 16))
        self.label_3.setObjectName("label_3")
        self.graphicsView_4 = PlotWidget(Dialog)
        self.graphicsView_4.setGeometry(QtCore.QRect(1090, 50, 256, 192))
        self.graphicsView_4.setObjectName("graphicsView_4")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(870, 470, 151, 20))
        self.label_4.setObjectName("label_4")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Graphe d\'angle en fct du temps"))
        self.label_2.setText(_translate("Dialog", "Graphe d\'energie cinétique"))
        self.label_3.setText(_translate("Dialog", "Portait de phase"))
        self.label_4.setText(_translate("Dialog", "Graphe d\'energie potentielle"))
from pyqtgraph import PlotWidget
